### ISSUE TITLE
position menu when scrolling

### ISSUE THREAD

**Issue by smoglica** [CodyHouse/cd-menu-changelog#1]
When the menu is visible and the page it's scrollable, when you scroll the menu doesn't update the position.

![chrome-capture](https://user-images.githubusercontent.com/17332096/72419973-2981c980-377e-11ea-94e2-bc1c9006f594.gif)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up.
We just pushed a new version of the component to fix the issue; now the menu element is hidden when user starts scrolling (the focus of the user is now moved to different content on the page so the menu can be closed).

Let me know if you are still having issues. Cheers!
